---
cache_dir: ~/Library/Caches/battleschool

sources:
  #local:
  #  - homebrew_playbook.yml

  url:
    - name: homebrew_playbook.yml
      url: https://raw.githubusercontent.com/vadimich/ansible-osx/master/homebrew_playbook.yml
      
    - name: dock_playbook.yml
      url: https://raw.githubusercontent.com/vadimich/ansible-osx/master/dock_playbook.yml 
  
  git:
    - name: 'osx'
      repo: 'https://github.com/vadimich/ansible-osx'
      playbooks:
         - homebrew.yml                 #must come before any use of homebrew module
