---
- hosts: workstation

  tasks:
    - name: remove all the current dock items
      sudo: false
      command: dockutil --remove all
      
    - name: add MailMate
      sudo: false
      command: dockutil --add ~/Applications/MailMate.app
      
    - name: add Chrome
      sudo: false
      command: dockutil --add ~/Applications/Google\ Chrome.app
      
    - name: add iTerm2
      sudo: false
      command: dockutil --add ~/Applications/iTerm.app
      
    - name: add Slack
      sudo: false
      command: dockutil --add ~/Applications/Slack.app
      
    - name: add Download folder
      sudo: false
      command: dockutil --add '~/Downloads' --view grid --display folder
      
    - name: Set dock to autohide
      sudo: false
      command: osascript -e "tell application \"System Events\" to set the autohide of the dock preferences to true"
