---
- hosts: workstation

  tasks:
    - name: remove all the current dock items
      sudo: false
      command: dockutil --remove all
      
    - name: add MailMate
      sudo: false
      command: dockutil --add ~/Applications/MailMate.app
      
    - name: add Chrome
      sudo: false
      command: dockutil --add ~/Applications/Google\ Chrome.app
      
    - name: add iTerm2
      sudo: false
      command: dockutil --add ~/Applications/iTerm.app
      
    - name: add Slack
      sudo: false
      command: dockutil --add ~/Applications/Slack.app
      
    - name: add Download folder
      sudo: false
      command: dockutil --add '~/Downloads' --view grid --display folder
      
    - name: Set dock to autohide
      sudo: false
      command: osascript -e "tell application \"System Events\" to set the autohide of the dock preferences to true"

# Launch apps on startup

    - name: launch on startup and hide MailMate
      sudo: false
      command: osascript -e 'tell application "System Events" to make new login item at end with properties {path:"/Users/vadimich/Applications/MailMate.app", name:"MailMate", hidden:true}'
      
    - name: launch on startup and hide Spectacle
      sudo: false
      command: osascript -e 'tell application "System Events" to make new login item at end with properties {path:"/Users/vadimich/Applications/Spectacle.app", name:"Spectacle", hidden:true}'
     
    - name: launch on startup and hide Dropbox
      sudo: false
      command: osascript -e 'tell application "System Events" to make new login item at end with properties {path:"/Users/vadimich/Applications/Dropbox.app", name:"Dropbox", hidden:true}'

    - name: launch on startup and hide Dashlane
      sudo: false
      command: osascript -e 'tell application "System Events" to make new login item at end with properties {path:"/Users/vadimich/Applications/Dashlane.app", name:"Dashlane", hidden:true}'

    - name: launch on startup and hide OmniFocus
      sudo: false
      command: osascript -e 'tell application "System Events" to make new login item at end with properties {path:"/Applications/OmniFocus.app", name:"OmniFocus", hidden:true}'
      
    - name: launch on startup and hide Tunnelblink
      sudo: false
      command: osascript -e 'tell application "System Events" to make new login item at end with properties {path:"/Applications/Tunnelblink.app", name:"Tunnelblink", hidden:true}'
      
    - name: launch on startup and hide Fantastical 2
      sudo: false
      command: osascript -e 'tell application "System Events" to make new login item at end with properties {path:"/Users/vadimich/Applications/Fantastical 2.app", name:"Fantastical 2", hidden:true}'
