---
- hosts: workstation

  tasks:
    - name: install homebrew_taps
      sudo: false
      homebrew_tap: tap=gapple/services,pivotal/tap,caskroom/cask

    - name: Install Homebrew recepies
      sudo: false
      homebrew: name={{item}}
      with_items:
        - dockutil
        - coreutils
        - tmux
        - autojump
        - the_silver_searcher

    - name: Install Homebrew Casks
      sudo: false
      homebrew_cask: name={{item}}
      with_items:
        - dashlane
        - spotify
        - vmware-fusion
        - virtualbox
        - fantastical
        - mailmate
        - google-chrome
        - dropbox
        - iterm2
        - spectacle
        - vagrant
        - slack
